db:
  host: localhost
  port: 6379
  db: 0
  password:

coinmarketcap:
  api_key: THISISASECRET
  sandbox: no

telegram:
  api_key: THISISASECRET
  users:
    - thisisausername

# Logging settings
logging:
  root_logging_level: INFO     # Root Logger logging level
  file_logging_level: INFO     # File Logger logging level
  console_logging_level: INFO  # Console Logger logging level
  other_loggers_enabled: yes  # Enable other loggers, besides main logger

