name: Pytest

on:
  pull_request:
    branches:
      - master

  workflow_run:
    workflows: [ "CI build" ]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . --no-cache-dir
      - name: Test with pytest
        env:
          TELEGRAM_BOT_NAME: ${{ secrets.TELEGRAM_BOT_NAME }}
          TELEGRAM_APP_ID: ${{ secrets.TELEGRAM_APP_ID }}
          TELEGRAM_APP_HASH: ${{ secrets.TELEGRAM_APP_HASH }}
          TELEGRAM_APP_SESSION: ${{ secrets.TELEGRAM_APP_SESSION }}
        run: |
          cd test && pytest
